name: Run tests and publish report
on:
  workflow_dispatch:
    inputs:
      suiteName:
        description: Enter Suite Name
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
#      url: https://dhivaagar.github.io/DemoProject/12/
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          ls
          mvn test -DsuiteName=${{ github.event.inputs.suiteName }}

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create reports directory
        run: mkdir -p uiReports/${{ steps.timestamp.outputs.timestamp }}

      - name: Copy Allure report
        run: |
          mkdir -p uiReports/${{ steps.timestamp.outputs.timestamp }}
          cp -R allure-report/. uiReports/${{ steps.timestamp.outputs.timestamp }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: uiReports/${{ steps.timestamp.outputs.timestamp }}
          publish_branch: gh-pages
          force_orphan: true

#      - name: Publish test report
#        uses: peaceiris/actions-gh-pages@v3
#        if: always()
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages
#          publish_dir: allure-history