name: Workflow Test

on:
  workflow_dispatch:

jobs:
  trigger:
    strategy:
      matrix:
        portals: [CM7, config7]
#    uses: Dhivaagar/DemoProject/.github/workflows/integration-Bat.yml@main
    uses: ./.github/workflows/integration-Bat.yml
    with:
      portalName: ${{ matrix.portals }}