name: MSP Mobile BAT workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests: [CM7, config7]
    steps:
      - name: Run workflow with appropriate portal name
        uses: ./.github/workflows/integration-Bat.yml
        with:
          portalName: ${{ matrix.tests }}
