name: one shot
on:
  workflow_dispatch:
    inputs:
      portalNames:
        description: "Portal Name"
        required: true
        type: string

      rallyTestSetIds:
        description: "Rally Test Set Ids"
        required: true
        type: string

      rallyBuildNos:
        description: "Rally Build Nos"
        required: true
        type: string

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Set up matrix
        id: set_matrix
        run: |
          IFS=',' read -ra PORTAL_ARRAY <<< "$(echo -n "${{ github.event.inputs.portalNames }}" | tr -d '[:space:]')"
          IFS=',' read -ra RALLY_TEST_SET_IDS_ARRAY <<< "$(echo -n "${{ github.event.inputs.rallyTestSetIds }}" | tr -d '[:space:]')"
          IFS=',' read -ra RALLY_BUILD_NOS_ARRAY <<< "$(echo -n "${{ github.event.inputs.rallyBuildNos }}" | tr -d '[:space:]')"
          MATRIX="["
          for i in "${!PORTAL_ARRAY[@]}"; do
            MATRIX+="{\"portalName\": \"${PORTAL_ARRAY[i]}\", \"rallyTestSetIds\": \"${RALLY_TEST_SET_IDS_ARRAY[i]}\", \"rallyBuildNos\": \"${RALLY_BUILD_NOS_ARRAY[i]}\"},"
          done
          MATRIX=${MATRIX::-1} # remove the last comma
          MATRIX+="]"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  run_tests:
    needs: generate_tests
    strategy:
      matrix:
        data: ${{fromJson(needs.generate_tests.outputs.matrix)}}
    uses: ./.github/workflows/integration-Bat.yml
    with:
      portalName: ${{ matrix.data.portalName }}
      rallyTestSetIds: ${{ matrix.data.rallyTestSetIds }}
      rallyBuildNos: ${{ matrix.data.rallyBuildNos }}
