on:
  workflow_dispatch:
    inputs:
      xmls:
        description: "xml names (comma separated)"
        required: true
        type: string

      shells:
        description: "shell names (comma separated)"
        required: true
        type: string

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Set up matrix
        id: set_matrix
        run: |
          IFS=',' read -ra XML_ARRAY <<< "${{ github.event.inputs.xmls }}"
          IFS=',' read -ra SHELL_ARRAY <<< "${{ github.event.inputs.shells }}"
          MATRIX=""
          for i in "${!XML_ARRAY[@]}"; do
            MATRIX+="xml: ${XML_ARRAY[i]}, shell: ${SHELL_ARRAY[i]}\\n"
          done
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  run_tests:
    needs: generate_tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        xml: ${{fromJson(needs.generate_tests.outputs.matrix)}}
    steps:
      - name: Run tests
        run: |
          echo "Running test for ${{ matrix.xml }}"
