name: MSP Mobile BAT workflow

on:
  workflow_dispatch:

jobs:

  CM7:
    uses: ./.github/workflows/integration-Bat.yml
    with:
      portalName: CM7
      suitesToRun: "['1', '2', '3', '4']"

  config7:
    uses: ./.github/workflows/integration-Bat.yml
    with:
      portalName: config7
      suitesToRun: "['5', '6', '7', '8']"
