name: MSP Mobile BAT workflow

on:
  workflow_dispatch:

jobs:
  build:
    outputs:
      portalName: ${{ steps.name.outputs.portalName }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests: [ CM7, config7 ]
    steps:
      - name: Run workflow with appropriate portal name
        id: name
        run: echo "portalName=${{ matrix.tests }}" >> $GITHUB_OUTPUT

  trigger:
    needs: build
    uses: ./.github/workflows/integration-Bat.yml
    with:
      portalName: ${{ needs.build.outputs.portalName }}
