name: MSP Mobile BAT workflow

on:
#  schedule:
#    - cron: '*/1 * * * 1-5'
#    - cron: '*/2 * * * 1-5'
#    - cron: '*/3 * * * 1-5'
#    - cron: '*/4 * * * 1-5'
  #    - cron: '30 0,1,22,23 * * 1-5'
  workflow_dispatch:
    inputs:
      env:
        description: Env to run on - qa/uat
        default: qa
        required: true
        type: string
      application_name:
        default: android
        description: Application to run on - Android/iOS
        required: true
        type: string
      app_Id:
        description: AppId to run on - Android/iOS
        required: true
        type: string

env:
  project: mysunpower-mobile
  androidAppIdQa: lt://APP10160601541707980658983933
  iosAppIdQa: lt://APP10160621531707980883915198
  androidAppIdUat: lt://APP10160601541707980658983933
  iosAppIdUat: lt://APP10160621531707980883915198

jobs:
  SetValueForScheduleRun:
    runs-on: ubuntu-latest
    outputs:
      applicationName: ${{ steps.set-values.outputs.applicationName }}
      appId: ${{ steps.set-values.outputs.appId }}
      runEnv: ${{ steps.set-values.outputs.runEnv }}
    steps:
      - name: Set Values
        id: set-values
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            case "${{ github.event.schedule }}" in
              "*/1 * * * 1-5")
                echo "applicationName=android" >> "$GITHUB_OUTPUT"
                echo "appId=${{ env.androidAppIdQa }}" >> "$GITHUB_OUTPUT"
                echo "runEnv=qa" >> "$GITHUB_OUTPUT"
                ;;
              "*/2 * * * 1-5")
                echo "applicationName=ios" >> "$GITHUB_OUTPUT"
                echo "appId=${{ env.androidAppIdUat }}" >> "$GITHUB_OUTPUT"
                echo "runEnv=uat" >> "$GITHUB_OUTPUT"
                ;;
              "*/3 * * * 1-5")
                echo "applicationName=android" >> "$GITHUB_OUTPUT"
                echo "appId=${{ env.androidAppIdQa }}" >> "$GITHUB_OUTPUT"
                echo "runEnv=qa" >> "$GITHUB_OUTPUT"
                ;;
              "*/4 * * * 1-5")
                echo "applicationName=ios" >> "$GITHUB_OUTPUT"
                echo "appId=${{ env.androidAppIdUat }}" >> "$GITHUB_OUTPUT"
                echo "runEnv=uat" >> "$GITHUB_OUTPUT"
                ;;
            esac
          fi
  LoginBatTest:
    needs: SetValueForScheduleRun
    uses: ./.github/workflows/integration-Bat.yml
    with:
      suiteName: LoginBatTest
      env: ${{ inputs.env || needs.SetValueForScheduleRun.outputs.runEnv }}
      application_name: ${{ inputs.application_name || needs.SetValueForScheduleRun.outputs.applicationName }}
      app_Id: ${{ inputs.app_Id || needs.SetValueForScheduleRun.outputs.appId }}

