name: Bat Test

on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        tests:
          - "[ 'BookAppointmentBacklogTest=cm3', 'CM3URLBacklogTest=cm3' ]"
          - "[ 'CM7BacklogRegistrationDateTest=cm3', 'CM7CappedPricingGuideGridListView=cm3' ]"

    uses: ./.github/workflows/integration-Bat.yml
    with:
      chunk: ${{ matrix.tests }}