name: Dynamic Environment Variables with Dynamic Loop Range

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start of the sequence'
        required: true
        default: 0
      end:
        description: 'End of the sequence'
        required: true
        default: 3

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      vars: ${{ steps.set-vars.outputs.vars }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set dynamic environment variables in a loop
        id: set-vars
        run: |
          start=${{ github.event.inputs.start }}
          end=${{ github.event.inputs.end }}
          output=""
          for i in $(seq $start $end); do
            echo "var_$i=$i" >> $GITHUB_ENV
            output="$output var_$i=$i"
          done
          
          # Save the variables as a single output string
          echo "vars=$output" >> $GITHUB_OUTPUT

  use-vars:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and use dynamic environment variables
        run: |
          vars="${{ needs.set-vars.outputs.vars }}"
          for var in $vars; do
            echo $var >> $GITHUB_ENV
          done
          
          # Print the dynamic environment variables
          for var in $vars; do
            var_name=$(echo $var | cut -d '=' -f 1)
            echo "$var_name=${!var_name}"
          done
