name: Bat Test

on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        tests:
          - [ { portalName: marketingPortal, suiteName: UpdateAudienceAfterPromoLaunch=marketingPortal }, { portalName: marketingPortal, suiteName: UpdateAudienceAfterPromoLaunch=marketingPortal } ]
          - [ { portalName: marketingPortal, suiteName: UpdateAudienceAfterPromoLaunch=marketingPortal }, { portalName: marketingPortal, suiteName: UpdateAudienceAfterPromoLaunch=marketingPortal } ]

    uses: ./.github/workflows/integration-Bat.yml
    with:
      chunk: ${{ matrix.tests }}