name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  process-lists:
    runs-on: ubuntu-latest
    outputs:
      sublists: ${{ steps.prepare-sublists.outputs.sublists }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare sublists
        id: prepare-sublists
        run: |
          # Define your nested lists here
          subLists=$(cat << 'EOF'
          [
            [
              "{ 'portalName': 'marketingPortal', 'suiteName': 'UpdateAudienceAfterPromoLaunch=marketingPortal' }",
              "{ 'portalName': 'marketingPortal', 'suiteName': 'UpdateAudienceAfterPromoLaunch=marketingPortal' }"
            ],
            [
              "{ 'portalName': 'marketingPortal', 'suiteName': 'UpdateAudienceAfterPromoLaunch=marketingPortal' }",
              "{ 'portalName': 'marketingPortal', 'suiteName': 'UpdateAudienceAfterPromoLaunch=marketingPortal' }"
            ]
          ]
          EOF
          )
          echo "sublists=$subLists" >> $GITHUB_OUTPUT

      - name: Trigger sub-workflow
        uses: actions/workflow-caller@v2
        with:
          workflow: trigger.yml
          arguments: '{"sublists": "${{ steps.prepare-sublists.outputs.sublists }}"}'
