name: Workflow Test

on:
  workflow_dispatch:

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Mapping:
          - portalName: CM7
            suitesToRun: "['1', '2', '3', '4']"

          - portalName: config7
            suitesToRun: "['5', '6', '7', '8']"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run integration test
        uses: ./.github/workflows/integration-Bat.yml
        with:
          portalName: ${{ matrix.Mapping.portalName }}
          suitesToRun: ${{ matrix.Mapping.suitesToRun }}
