name: Bat Test

on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
#        tests: [ "[ '{ 'portalName': 'marketingPortal', 'suiteName': 'UpdateAudienceAfterPromoLaunch=marketingPortal' }', '{ 'portalName': 'marketingPortal', 'suiteName': 'UpdateAudienceAfterPromoLaunch=marketingPortal' }' ]", "[ '{ 'portalName': 'marketingPortal', 'suiteName': 'UpdateAudienceAfterPromoLaunch=marketingPortal' }', '{ 'portalName': 'marketingPortal', 'suiteName:' 'UpdateAudienceAfterPromoLaunch=marketingPortal' }' ]" ]
        tests:
          - portalName: marketingPortal
            suiteName: UpdateAudienceAfterPromoLaunch=marketingPortal
          - portalName: marketingPortal
            suiteName: UpdateAudienceAfterPromoLaunch=marketingPortal

#    uses: ./.github/workflows/integration-Bat.yml
#    with:
#      chunk: ${{ matrix.tests }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Integration Test
        run: |
          echo "Running integration test for chunk ${{ matrix.tests }}"