name: Single Run
on:
  workflow_dispatch:
    inputs:
      portalNames:
        description: "Portal Names (comma separated)"
        required: true
        type: string
      rallyTestSetIds:
        description: "Rally Test Set IDs (comma separated)"
        required: true
        type: string

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      portal_to_rally: ${{ steps.set_matrix.outputs.portal_to_rally }}
    steps:
      - name: Set up matrix
        id: set_matrix
        run: |
          # Read and split inputs
          IFS=',' read -ra PORTAL_ARRAY <<< "$(echo -n "${{ github.event.inputs.portalNames }}" | tr -d '[:space:]')"
          IFS=',' read -ra RALLY_TEST_SET_IDS_ARRAY <<< "$(echo -n "${{ github.event.inputs.rallyTestSetIds }}" | tr -d '[:space:]')"

          # Initialize JSON structure for the matrix
          matrix="["

          # Initialize associative array for portal to rally test set mapping
          declare -A PORTAL_TO_RALLY_TEST_SET_MAP
          
          # Build JSON array and map
          for i in "${!PORTAL_ARRAY[@]}"; do
            suites=$(yq e ".suites" "./scripts/portals/${PORTAL_ARRAY[i]}.yml" | sed 's/^- //; s/^/'\''/; s/$/'\''/' | paste -sd, - | sed 's/^/[ /; s/$/ ]/')
            echo "suites: $suites"
            IFS=',' read -ra SUITE_ARRAY <<< "$suites"
            for suite in "${SUITE_ARRAY[@]}"; do
              matrix+="{\"portalName\": \"${PORTAL_ARRAY[i]}\", \"suiteName\": ${suite}},"
            done
            PORTAL_TO_RALLY_TEST_SET_MAP["${PORTAL_ARRAY[i]}"]="${RALLY_TEST_SET_IDS_ARRAY[i]}"
          done

          # Remove the last comma and close the JSON array
          matrix=${matrix::-1}
          matrix+="]"

          # Convert the associative array to JSON
          portal_to_rally="{"
          for portal in "${!PORTAL_TO_RALLY_TEST_SET_MAP[@]}"; do
            portal_to_rally+="\"$portal\":\"${PORTAL_TO_RALLY_TEST_SET_MAP[$portal]}\","
          done
          portal_to_rally=${portal_to_rally::-1}
          portal_to_rally+="}"

          # Output the JSON structures
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "portal_to_rally=$portal_to_rally" >> $GITHUB_OUTPUT

  run_tests:
    needs: generate_tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ${{fromJson(needs.generate_tests.outputs.matrix)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          portalName=${{ matrix.config.portalName }}
          suiteName=${{ matrix.config.suiteName }}
          portal_to_rally='${{ needs.generate_tests.outputs.portal_to_rally }}'
          rallyTestSetId=$(echo "$portal_to_rally" | jq -r --arg portal "$portalName" '.[$portal]')
          echo "Running portal $portalName with suite $suiteName and Rally Test Set ID $rallyTestSetId"
