name: Single Run
on:
  workflow_dispatch:
    inputs:
      portalNames:
        description: "Portal Names (comma separated)"
        required: true
        type: string

      rallyTestSetIds:
        description: "Rally Test Set IDs (comma separated)"
        required: true
        type: string

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Set up matrix
        id: set_matrix
        run: |
          # Read and split inputs
          IFS=',' read -ra PORTAL_ARRAY <<< "$(echo -n "${{ github.event.inputs.portalNames }}" | tr -d '[:space:]')"
          IFS=',' read -ra RALLY_TEST_SET_IDS_ARRAY <<< "$(echo -n "${{ github.event.inputs.rallyTestSetIds }}" | tr -d '[:space:]')"

          # Initialize JSON structure
          matrix="["

          # Build JSON array
          for i in "${!PORTAL_ARRAY[@]}"; do
            matrix+="{\"portalName\": \"${PORTAL_ARRAY[i]}\", \"rallyTestSetId\": \"${RALLY_TEST_SET_IDS_ARRAY[i]}\"},"
          done

          # Remove the last comma and close the JSON array
          matrix=${matrix::-1}
          matrix+="]"

          # Output the JSON structure
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run_tests:
    needs: generate_tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ${{ fromJson(needs.generate_tests.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          portalName=${{ matrix.config.portalName }}
          rallyTestSetId=${{ matrix.config.rallyTestSetId }}
          echo "Running portal $portalName with Rally Test Set ID $rallyTestSetId"
