name: CI

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip -q /tmp/chromedriver.zip -d /tmp
          chmod +x /tmp/chromedriver
        # Change permissions to executable

      - name: Set up ChromeDriver
        run: echo "::add-path::/tmp"
        # Add ChromeDriver path to PATH

      - name: Verify ChromeDriver
        run: chromedriver --version
          # Verify ChromeDriver installation

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set Execution Policy (Not Recommended)
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser  # Replace with the desired policy if needed
      # Rest of your workflow steps...

      - name: Build and Test
        run: |
          mvn clean install
          mvn test -Dtest=selenium.ExampleTest
