name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
        # Verify the ChromeDriver installation by running it

      #      - name: Set Execution Policy (Not Recommended)
      #        run: |
      #          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser  # Replace with the desired policy if needed
      #      # Rest of your workflow steps...

      - name: Build and Test
        run: |
          mvn clean install
          mvn test -Dtest=selenium.ExampleTest