name: Browser SetUp Test

on:
  repository_dispatch:
    types: Sample

  workflow_dispatch:

jobs:
  selenium_tests:
    runs-on: self-hosted  # Specify your self-hosted runner here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          w
          who
          whoami
          sudo apt update
          sudo apt install maven

      - name: Build and Test
        run: |
          sudo mvn clean install -Dmaven.test.skip=true -Dskipjar=true
          sudo mvn test -Dtest=selenium.ExampleTest

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/