name: CI

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set Execution Policy (Not Recommended)
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser  # Replace with the desired policy if needed
      # Rest of your workflow steps...

      - name: Build and Test
        run: mvn test -Dtest=selenium.ExampleTest
