name: Browser SetUp Test

on:
  repository_dispatch:
    types: Sample

  workflow_dispatch:

jobs:
  selenium_tests:
    runs-on: self-hosted  # Specify your self-hosted runner here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Build and Test
        run: |
          mvn clean install -Dmaven.test.skip=true -Dskipjar=true
          mvn test -Dtest=selenium.ExampleTest

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/