name: Browser Setup Test

on:
  repository_dispatch:
    types: browserSetUpTest
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        default: chrome
        options:
          - chrome
          - firefox
          - edge
      env:
        type: choice
        description: Which environment to test
        required: true
        default: dev
        options:
          - qa
          - uat
          - dev
      platform:
        type: choice
        description: Which platform to test
        required: true
        default: mac
        options:
          - windows
          - mac
          - linux

jobs:
  selenium_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Parameters
        run: |
          echo "Params are Params are Browser=${{github.event.inputs.browser}} Env=${{github.event.inputs.env}} Platform=${{github.event.inputs.platform}}"      

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y
          google-chrome --version
          Xvfb :99 -ac -screen 0 1280x1024x24 & 
          export DISPLAY=:99

      - name: Build
        run: |
          mvn clean install -Dmaven.test.skip=true -Dskipjar=true

      - name: Test
        run: |
          export DISPLAY=:99
          mvn -X test -Dtest=com.test.automation.BrowserSetupTest


      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/
