name: Browser SetUp Test

on:
  repository_dispatch:
    types: Sample

  workflow_dispatch:

jobs:
  selenium_tests:
    runs-on: self-hosted  # Specify your self-hosted runner here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          mvn clean install -Dmaven.test.skip=true -Dskipjar=true
          google-chrome --version
          google-chrome
#          mvn test -Dtest=selenium.ExampleTest

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/