name: IntegrationTest

'on':
  workflow_call:
    inputs:
      portalName:
        required: true
        description: suite to run
        type: string
      suitesToRun:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      portalName:
        description: suite to run
        required: true
        type: string
      suitesToRun:
        description: "The suites which needs to be run i.e., for single suite run format: ['suiteName'],
          multiple suite run format: ['suiteName1', 'suiteName2']"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        tests: ${{ fromJson(inputs.suitesToRun) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests for ${{ matrix.tests }} in portal ${{ inputs.portalName }}"