name: IntegrationTest

on:
  workflow_call:
    inputs:
      chunk:
        description: chunk data
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo ${{ inputs.chunk }}
  integration:
    strategy:
      fail-fast: false
      matrix:
        tests: ${{ fromJSON(inputs.chunk) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Integration Test
        run: |
          echo "Running integration test for chunk ${{ matrix.tests }}"
