name: IntegrationTest

on:
  workflow_call:
    inputs:
      chunk:
        description: chunk data
        required: true
        type: string

jobs:
  metadata:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        tests: ${{ fromJSON(inputs.chunk) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Integration Test
        run: |
          echo "Running integration test for chunk ${{ matrix.tests }} "