name: BatIntegrationTest

'on':
  workflow_call:
    inputs:
      portalName:
        required: true
        description: suite to run
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CM7: [1, 2, 3, 4]
        config7: [5, 6, 7, 8]
    steps:
      - uses: actions/checkout@v3

      - name: Run workflow with appropriate portal name
        run: |
          echo ${{ inputs.portalName }}
          echo ${{ matrix.inputs.portalName }}
