name: Triggered Workflow

on:
  workflow_call:
    inputs:
      sublists:
        type: string
        required: true

jobs:
  process-sublists:
    strategy:
      matrix:
        sublist: ${{fromJson(inputs.sublists)}}
    runs-on: ubuntu-latest
    steps:
      - name: Process sublist
        run: |
          echo "Processing sublist ${{ matrix.sublist }}"
