name: BatIntegrationTest

'on':
  workflow_call:
    inputs:
      portalName:
        required: true
        description: suite to run
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        CM7: [1, 2, 3, 4]
        config7: [5, 6, 7, 8]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.inputs.portalName }} 
          echo ${{ inputs.portalName }}