name: BatIntegrationTest

'on':
  workflow_call:
    inputs:
      portalName:
        required: true
        description: suite to run
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.portalName }}