name: IntegrationTest

'on':
  workflow_call:
    inputs:
      portalName:
        required: true
        description: suite to run
        type: string
  workflow_dispatch:
    inputs:
      portalName:
        description: suite to run
        required: true
        type: string
      suitesToRun:
        description: "The suites which needs to be run i.e., for single suite run format: ['suiteName'], multiple suite run format: ['suiteName1', 'suiteName2']"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      suitesToRun: ${{ steps.read-yaml.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install
          npm install js-yaml
          npm install fs

      - name: Read list from YAML
        id: read-yaml
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const fileContents = fs.readFileSync('list.yml', 'utf8');
            const data = yaml.load(fileContents);
            console.log("Data: ", data);
            console.log("Formatted Data:", JSON.stringify(JSON.parse(JSON.stringify(data.items))));
            return JSON.stringify(JSON.parse(JSON.stringify(data.items)));


  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests: ${{ fromJson(needs.build.outputs.suitesToRun) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests for ${{ matrix.tests }} in portal ${{ github.event.inputs.portalName }}"
