name: IntegrationTest

'on':
  workflow_call:
    inputs:
      portalName:
        required: true
        description: suite to run
        type: string
  workflow_dispatch:
    inputs:
      portalName:
        description: suite to run
        required: true
        type: string
      suitesToRun:
        description: "The suites which needs to be run i.e., for single suite run format: ['suiteName'], multiple suite run format: ['suiteName1', 'suiteName2']"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      suitesToRun: ${{ steps.set-suites.outputs.suitesToRun }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Set suitesToRun
        id: set-suites
        run: |
          if [ -z "${{ github.event.inputs.suitesToRun }}" ]; then
            echo "No suitesToRun provided, reading from list.yml"
            suites=$(yq -o=json '.items' list.yml)
            echo "suitesToRun=${suites}" >> $GITHUB_OUTPUT
          else
            echo "suitesToRun=${{ inputs.suitesToRun }}" >> $GITHUB_OUTPUT
          fi

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        tests: ${{ fromJson(needs.build.outputs.suitesToRun) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests for ${{ matrix.tests }} in portal ${{ github.event.inputs.portalName }}"
