name: IntegrationTest

on:
  workflow_call:
    inputs:
      chunk:
        description: chunk data
        required: true
        type: string

jobs:
  metadata:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests: ${{ fromJson(inputs.chunk) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Integration Test
        run: |
          echo ${{ matrix.tests }}