# .github/workflows/main.yml
name: Get List from YAML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install js-yaml

      - name: Read list from YAML
        id: read-yaml
        run: |
          node -e "const fs = require('fs'); const yaml = require('js-yaml'); const fileContents = fs.readFileSync('list.yml', 'utf8'); const data = yaml.load(fileContents); console.log(`::set-output name=matrix::${JSON.stringify(data.items)}`);"

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        item: ${{ fromJson(needs.build.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running tests for ${{ matrix.item }}"
