name: Convert yml to single line

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: convert YAML to single line
        id: convert
        run: |          
          # Update buildspec
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          sudo wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /usr/local/bin/jq
          sudo chmod +x /usr/local/bin/jq
          build_spec_content=$(yq -o=json '.' scripts/commonBuildSpec.yml | jq -c '.')
          echo "::set-output name=updated-buildspec::$build_spec_content"
          echo "-------------------------------------------------------------------------------------"
          echo "${build_spec_content}"
          echo "-------------------------------------------------------------------------------------"

      - name: Print buildspec
        run: echo "${{ steps.convert.outputs.updated-buildspec }}"
