# .github/workflows/main.yml
name: Get list from YAML

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        item: []

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read list from YAML
        id: read-yaml
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const fileContents = fs.readFileSync('list.yml', 'utf8');
            const data = yaml.load(fileContents);
            return data.items;

      - name: Set matrix
        run: echo "matrix={\"item\":${{ toJson(steps['read-yaml'].outputs.result)}}}" >> $GITHUB_ENV

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(env.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running tests for ${{ matrix.item }}"
