name: Get list from YAML

on:
  workflow_dispatch:

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    outputs:
#      matrix: ${{ steps.read-yaml.outputs.result }}
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '14'
#
#      - name: Install dependencies
#        run: |
#          npm install
#          npm install js-yaml
#          npm install fs
#
#      - name: Read list from YAML
#        id: read-yaml
#        uses: actions/github-script@v6
#        with:
#          script: |
#            const fs = require('fs');
#            const yaml = require('js-yaml');
#            const fileContents = fs.readFileSync('cm3.yml', 'utf8');
#            const data = yaml.load(fileContents);
#            console.log(JSON.stringify(JSON.parse(JSON.stringify(data.items))));
#            return JSON.stringify(JSON.parse(JSON.stringify(data.items)));

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read-list.outputs.MY_LIST }}
    steps:
      - name: Read list from YAML
        id: read-list
        run: |
          MY_LIST=$(yq '.items' list.yml)
          ECHO 
          echo "MY_LIST=$MY_LIST" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        item: ${{ fromJson(needs.build.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests for ${{ matrix.item }}"
