name: Workflow URl Test
on:
  workflow_dispatch:
permissions:
  actions: read
  contents: read
jobs:
  build:
    strategy:
      matrix:
        distro: [alpha, beta, gamma]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Some Scripts
        run: echo "do something here ${{ matrix.distro }}"

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v1
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: "build (${{ matrix.distro }})" # input job.<job-id>.name and matrix here.

      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.html_url }}