name: Manage Tags

on:
  workflow_dispatch:

jobs:
  manage-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get all tags
        id: get-tags
        run: |
          tags=$(git tag -l | sort -V)
          tags=$(echo $tags | tr '\n' ' ')
          echo "::set-output name=tags::$tags"

      - name: Create a new tag
        run: |
          current_date=$(date +"%d/%m/%Y")
          new_tag="Backup-$current_date"
          git tag $new_tag
          git push origin $new_tag

      - name: Delete oldest tag if there are more than 5 tags
        run: |
          tags="${{ steps.get-tags.outputs.tags }}"
          tags_array=($tags)
          if [ ${#tags_array[@]} -gt 5 ]; then
            echo "tags=${tags_array[@]}"
            while [ ${#tags_array[@]} -gt 5 ]; do
              oldest_tag=${tags_array[0]}
              git tag -d $oldest_tag
              git push origin :refs/tags/$oldest_tag
              echo "Deleted oldest tag: $oldest_tag"
              tags_array=("${tags_array[@]:1}")
            done
          fi
