name: Manage Tags

on:
  workflow_dispatch:

jobs:
  manage-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get all tags
        id: get-tags
        run: |
          tags=$(git tag -l | sort -V)
          echo "tags=$tags" >> $GITHUB_ENV

      - name: Delete oldest tag if there are more than 5 tags
        run: |
          tags=(${{ env.tags }})
          if [ ${#tags[@]} -gt 5 ]; then
            echo "tags=${tags[@]}"
            while [ ${#tags[@]} -gt 5 ]; do
              oldest_tag=${tags[0]}
              git tag -d $oldest_tag
              git push origin --delete :$oldest_tag
              echo "Deleted oldest tag: $oldest_tag"
              tags=("${tags[@]:1}")
            done
          fi
