name: Manage Tags

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  manage-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          new_tag=$(date +%Y%m%d%H%M%S)
          git tag $new_tag
          git push origin $new_tag

      - name: Get all tags
        id: get-tags
        run: |
          tags=$(git tag -l | sort -V)
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Delete oldest tag if there are more than 30 tags
        if: ${{ steps.get-tags.outputs.tags }}
        run: |
          tags=(${GITHUB_ENV.tags})
          if [ ${#tags[@]} -gt 30 ]; then
            oldest_tag=${tags[0]}
            git tag -d $oldest_tag
            git push origin --delete $oldest_tag
          fi
