name: Manage Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  manage-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new tag
        run: |
          new_tag=$(date +%Y%m%d%H%M%S)
          git tag $new_tag
          git push origin $new_tag

      - name: Get all tags
        id: get-tags
        run: |
          tags=$(git tag -l | sort -V)
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Delete oldest tag if there are more than 5 tags
        if: ${{ steps.get-tags.outputs.tags }}
        run: |
          tags=(${{ steps.get-tags.outputs.tags }})
          while [ ${#tags[@]} -gt 5 ]; do
            oldest_tag=${tags[0]}
            git tag -d $oldest_tag
            git push origin --delete :$oldest_tag
            echo "Deleted oldest tag: $oldest_tag"
            tags=("${tags[@]:1}")
          done
          
          if [ ${#tags[@]} -gt 5 ]; then
            oldest_tag=${tags[0]}
            git tag -d $oldest_tag
            git push origin --delete $oldest_tag
          fi
