name: Automation API Trigger Test

on:
  repository_dispatch:
    types: ApiTrigger

  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        default: chrome
        options:
          - chrome
          - firefox
          - edge
      myParam:
        type: choice
        description: 'Example parameter'
        required: true
        default: params
        options:
          - params
          - args

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Print Parameter
        run: echo "My parameter is ${{ github.event.client_payload.param1 }} and my browser is ${{ github.event.client_payload.browser1 }}"

#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build and Test
#        run: |
#          mvn clean install
#          mvn test -Dsuite=selenium.ExampleTest
#
#      - name: Trigger Workflow with Parameters
#        if: github.event_name == 'workflow_dispatch'  # Only trigger on workflow_dispatch
#        run: |
#          curl -X POST \
#            -H "Accept: application/vnd.github.v3+json" \
#            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            https://api.github.com/repos/Dhivaagar/DemoProject/dispatches \
#             -d '{"event_type": "ApiTrigger", "client_payload": {"param1": "${{ github.event.inputs.myParam }}", "browser1": "${{ github.event.inputs.browser }}"}}'
#
#      - uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: screenshots
#          path: screenshots/
