name: Automation API Trigger Test

on:
  repository_dispatch:
    types: ApiTrigger

  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        default: chrome
        options:
          - chrome
          - firefox
          - edge
      myParam:
        type: choice
        description: 'Example parameter'
        required: true
        default: params
        options:
          - params
          - args

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fetch all branches
        run: git fetch --all

      - name: Change branch
        if : github.event_name == 'repository_dispatch'
        run: git checkout ${{ github.event.client_payload.branch }}

      - name: Print Parameter
        run: echo "My parameter is ${{ github.event.client_payload.param1 }} branch ${{ github.event.client_payload.branch }} and my browser is ${{ github.event.client_payload.browser1 }}"

      - name: Build and Test
        run: |
              mvn clean install -Dmaven.test.skip=true -Dskipjar=true
              mvn test '-Dtest=SimpleTest'

